### ISSUE TITLE
Subdomains not reliably detected

### ISSUE THREAD

**Issue by johtso** [vantezzen/dontbugme#15]
**Describe the bug**
Top level domain isn't properly detected.

**To Reproduce**
Try on https://7plus.com.au/

The domain is detected as being `com.au`

https://publicsuffix.org/
https://github.com/lupomontero/psl
https://github.com/lupomontero/psl/blob/master/dist/psl.min.js

**Comment by vantezzen** [comment]
Duplicate of #8.

I am currently working on DontBugMe 2 which allows choosing what domain should be used:

<img width="260" alt="Screenshot 2021-08-04 at 13 47 09" src="https://user-images.githubusercontent.com/10333196/128175490-0c4bbdfe-591c-4e64-9056-6fc558f2ec82.png">
