### ISSUE TITLE
[Translation] pt_PT

### ISSUE THREAD

**Issue by efernandesng** [vantezzen/dontbugme#2]
Language: Portuguese (Portugal)

"DontBugMe allows you to easily use credentials from BugMeNot.com on any page."

=> "DontBugMe facilita a utilização de credenciais do BugMeNot.com em qualquer página."

"It looks like there are no logins availible for this page."

=> "Aparentemente não há contas disponíveis para esta página."

"Click any result to fill it into the page."

=> "Clique em qualquer resultado para o preencher na página."

"Automatically submit"

=> "Submeter automaticamente"

"Automatically check for availible accounts and show badge"

=> "Verificar automaticamente por contas disponíveis e mostrar sinalização"

"Results provided by BugMeNot.com. This extension is not affiliated with BugMeNot."

=> "Resultados fornecidos por BugMeNot.com. Esta extensão não tem qualquer tipo de filiação com o BugMeNot."

================================================================================

"DontBugMe allows you to easily use credentials from BugMeNot.com on any page. 
Simply click the "DontBugMe" icon in your toolbar on any login-page and DontBugMe will search for any available credentials. Then simply click on any of the results to automatically insert them into your current page.

The full source code of this extension is available on https://github.com/vantezzen/dontbugme, if you find any issues or have a question please visit https://github.com/vantezzen/dontbugme/issues.

This extension needs the following permissions:
- "http://bugmenot.com/view/*"(=> "Read and change you data on bugmenot.com") to get credentials for the current site from BugMeNot
- "activeTab/tabs"(=> "Access browser tabs") to insert login credentials into your current page.

We do not collect or save any usage or other data about the users of this extension.

Help us translate DontBugMe into your language by providing your translation at https://github.com/vantezzen/dontbugme/issues/new?assignees=&labels=&template=provide-translation.md&title=%5BTranslation%5D+LANGUAGE

If you like this extension you may also like "Ew, Mail!" which allows you to easily insert temp-mail.org addresses into any website. "Ew, Mail!" is availible on https://addons.mozilla.org/en-US/firefox/addon/ew-mail/.

This extension is not affiliated to BugMeNot.com in any way."

**Comment by vantezzen** [comment]
Thank you very much for your translation, I will publish a new update with it the coming days.

**Comment by vantezzen** [comment]
I published version 1.10 today, implementing your translation. The version is currently going through review and should be availible soon.
