### ISSUE TITLE
[Translation] Simplified Chinese

### ISSUE THREAD

**Issue by vampv** [vantezzen/dontbugme#6]
Language: 简体中文（Simplified Chinese）

"DontBugMe allows you to easily use credentials from BugMeNot.com on any page."

=> "DontBugMe 能帮你在任何页面上轻松地使用BugMeNot.com上提供的登录凭证。"

"It looks like there are no logins availible for this page."

=> "有时候有些页面看起来似乎没有可用的登录信息。"

"Click any result to fill it into the page."

=> "单击其中任一结果，将其填写到页面中。"

"Automatically submit"

=> "它就会自动发送。"

"Automatically check for availible accounts and show badge"

=> "自动检查可用的账号并将其显示出来"

"Results provided by BugMeNot.com. This extension is not affiliated with BugMeNot."

=> "登录结果由BugMeNot.com提供，但此扩展不属于BugMeNot"

================================================================================

"DontBugMe allows you to easily use credentials from BugMeNot.com on any page. 
Simply click the "DontBugMe" icon in your toolbar on any login-page and DontBugMe will search for any available credentials. Then simply click on any of the results to automatically insert them into your current page.

The full source code of this extension is available on https://github.com/vantezzen/dontbugme, if you find any issues or have a question please visit https://github.com/vantezzen/dontbugme/issues.

This extension needs the following permissions:
- "http://bugmenot.com/view/*"(=> "Read and change you data on bugmenot.com") to get credentials for the current site from BugMeNot
- "activeTab/tabs"(=> "Access browser tabs") to insert login credentials into your current page.

We do not collect or save any usage or other data about the users of this extension.

Help us translate DontBugMe into your language by providing your translation at https://github.com/vantezzen/dontbugme/issues/new?assignees=&labels=&template=provide-translation.md&title=%5BTranslation%5D+LANGUAGE

If you like this extension you may also like "Ew, Mail!" which allows you to easily insert temp-mail.org addresses into any website. "Ew, Mail!" is availible on https://addons.mozilla.org/en-US/firefox/addon/ew-mail/.

This extension is not affiliated to BugMeNot.com in any way."

**Comment by vantezzen** [comment]
Thank you for your help in translating DontBugMe. Your translations will be published with one of the next releases.

**Comment by vantezzen** [comment]
Just published 1.12 with your additions - thank you again!
