### ISSUE TITLE
[Feature request] Voting

### ISSUE THREAD

**Issue by kubalav** [vantezzen/dontbugme#7]
Can you add voting for particular login data and sort by success rate?

**Comment by vantezzen** [comment]
Logins should normally already be sorted by success rate as seen on the colored dots on the left side.

**Comment by kubalav** [comment]
What about voting?

**Comment by vantezzen** [comment]
Voting is not currently implemented, no.

**Comment by kubalav** [comment]
Is it planned?

**Comment by vantezzen** [comment]
It is not currently planned but it looks like it would be possible to implement such a functionality.

**Comment by vantezzen** [comment]
<img width="328" alt="Screenshot 2021-08-05 at 09 48 17" src="https://user-images.githubusercontent.com/10333196/128312314-40117e8c-2adb-4105-9a4c-5b6e47cd2d49.png">

This feature will be implemented in the new DontBugMe 2 Update. After using credentials, you will be asked if the credentials worked.
