### ISSUE TITLE
Opera extension is available, but the button is disabled?

### ISSUE THREAD

**Issue by darylrobert** [vantezzen/dontbugme#9]
https://addons.opera.com/en-gb/extensions/details/dontbugme/

Also, I gotta COMM! I'm COMMING!
![dontbugme vantezzen io_](https://user-images.githubusercontent.com/61579747/82202482-8d86eb00-9934-11ea-8243-ee28d09ec8f0.png)

**Comment by vantezzen** [comment]
Thank you for the feedback, I just published a new update to the website.
